### ISSUE TITLE
Does QuartzDB respect date_default_timezone_set?

### ISSUE THREAD

**Issue by nitinthewiz** [aaronpk/QuartzDB#4]
I tried to get it to respect that we're in PST, but it doesn't seem to accept it -

date_default_timezone_set('America/Los_Angeles');

It seems somewhere in there, there's code to upend it by changing the default to UTC. Is the expectation that we would go in there and change it to PST if we need it?

I understand that you're saving data strictly based on UTC time, but it really screws up almost all data retrieval for me!

What's your workaround for that?

**Comment by aaronpk** [comment]
QuartzDB explicitly stores everything in UTC, in order to have control over the date-based sharding and retrieval. If you're reading the files directly you'll need to account for this. The API it provides will take timezones into account, so for example you can use the [query method](https://github.com/aaronpk/QuartzDB#querying) and pass in a local timestamp that includes a timezone offset and you'll get back the right results. I strongly recommend not reading the storage files directly and instead using the API that QuartzDB provides.

**Comment by nitinthewiz** [comment]
I'm using the API, just not providing the timezone offset I think. Will try that... Thanks!
